export const perros = [
    {
        id: 1,
        img: "https://i.ibb.co/JFfvWGP/perros-4.png",
        name: "Chester",
        type:"Dog",
        race: "Golden retriever",
        history:"Chester es un perrito muy travieso y juguetón, el espacio de nuestra casa es muy pequeña por eso nuestra misión es encontrar la familia ideal para él y seguro que tú eres la persona indicada.",
        personality:["Cariñoso", "Inquieto", "Juguetón"],
        personalityImg:["https://i.ibb.co/XjwrCqd/cari-oso.png", 
                        "https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"Los Ageles California",
        ubication:"200-242 E Compton Blvd, Compton,",
        age:"2 Meses",
        sex:"male"

    },
    {
        id: 2,
        img: "https://i.ibb.co/k5DjwmG/perros-3.png",
        name: "Papi",
        type:"Dog",
        race: "Chihuahua",
        history:"Papi es un perrito feliz y amoroso, tenemos muchos animales y lo molesta por eso nuestra misión es encontrar la familia ideal para él y seguro que tú eres la persona indicada.",
        personality:["Cariñoso", "Inquieto", "Juguetón"],
        personalityImg:["https://i.ibb.co/XjwrCqd/cari-oso.png", 
                        "https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"Texas",
        ubication:"2900-2908 Hickory St, Dallas,",
        age:"1 Mes",
        sex:"male"
    },
    {
        id: 3,
        img: "https://i.ibb.co/3fvNWbh/perros-1.png",
        name: "Rocky",
        type:"Dog",
        race: "Rottweiler",
        history:"Rocky es un perrito muy lindo y cariñoso, tiene 5 hermanitos más y por cuestiones de espacio y tiempo no podremos cuidar a todos, nuestra misión es encontrar la familia ideal para él y seguro que tú eres la persona indicada.",
        personality:["Cariñoso", "Inquieto", "Juguetón"],
        personalityImg:["https://i.ibb.co/XjwrCqd/cari-oso.png", 
                        "https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"New Mexico 31134",
        ubication:"4140 Parker Rd. Allentown,",
        age:"3 Meses",
        sex:"male"
    },
    {
        id: 4,
        img: "https://i.ibb.co/0KH02v4/perros-2.png",
        name: "Pelusa",
        type:"Dog",
        race: "Bichón frisé",
        history:"Pelusa es una perrita muy jugetona y cariñosa, viajamos mucho y no podemos cuidarla por eso nuestra misión es encontrar la familia ideal para él y seguro que tú eres la persona indicada.",
        personality:["Cariñoso", "Inquieto", "Juguetón"],
        personalityImg:["https://i.ibb.co/XjwrCqd/cari-oso.png", 
                        "https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"New York",
        ubication:"Lower Clinton Hill,",
        age:"2 Meses",
        sex:"female"
    },
]
export const gatos = [
    {
        id: 5,
        img: "https://i.ibb.co/f0YvVjg/gatos-2.png",
        name: "Matilde",
        type:"Cat",
        race: "British Shorthair",
        history:"Matilde es la mejor guarda espaldas, siempre esta hay para conversar y recibirá cada día con un fuerte cariño. Fue rescatada y busco una persona que le pueda dar todo el amor que ella necesita.",
        personality:["Juguetón", "Inquieto", "Tierno"],
        personalityImg:["https://i.ibb.co/9gJ9mb8/jugueton.png",
                        "https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/KWPh90s/tierno.png"],
        city:"4140 Parker Rd. Allentown,",
        ubication:"New Mexico 31134",
        age:"6 Meses",
        sex:"female"

    },
    {
        id: 6,
        img: "https://i.ibb.co/Ttsdm1V/gatos-4.png",
        name: "Pelusa",
        type:"Cat",
        race: "Birmano",
        history:"pelusa es un gato jugeton de 4 meses, que está buscando una familia que lo quiera y cuide mucho. Es muy cariñoso y le gusta mucho que lo acaricien.Pelusa se lleva muy bien con otros gatos y perros, y bebes.",
        personality:["Cariñoso", "Tierno", "Juguetón"],
        personalityImg:["https://i.ibb.co/XjwrCqd/cari-oso.png", 
                        "https://i.ibb.co/KWPh90s/tierno.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"Texas",
        ubication:"2900-2908 Hickory St, Dallas,",
        age:"1 Mes",
        sex:"male"
    },
    {
        id: 7,
        img: "https://i.ibb.co/znrhfpz/gatos-3.png",
        name: "Kity",
        type:"Cat",
        race: "Bombay",
        history:"Kity es una gata joven y juguetona que busca un hogar en el que pasar el resto de su vida. Es cariñosa y amorosa, y le encanta la compañia con otros aninimales !!!",
        personality:["Inquieto", "Tierno", "Juguetón"],
        personalityImg:["https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/KWPh90s/tierno.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"New Mexico 31134",
        ubication:"4140 Parker Rd. Allentown,",
        age:"3 Meses",
        sex:"female"
    },
    {
        id: 8,
        img: "https://i.ibb.co/qpzYwPD/gatos-1.png",
        name: "Bombón",
        type:"Cat",
        race: "Gato americano",
        history:"Bombon es un gato inquieto de 6 meses, le gusta jugar con otros animales y es muy cariñoso. ama a los bebés duerme mucho, no tenemos espacio para el asi que estamos buscando una familia para el.",
        personality:["Cariñoso", "Inquieto", "Juguetón"],
        personalityImg:["https://i.ibb.co/XjwrCqd/cari-oso.png", 
                        "https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"New York",
        ubication:"Lower Clinton Hill,",
        age:"2 Meses",
        sex:"male"
    },
]
export const mascotas =[
    {
        id: 1,
        img: "https://i.ibb.co/JFfvWGP/perros-4.png",
        name: "Chester",
        type:"Dog",
        race: "Golden retriever",
        history:"Chester es un perrito muy travieso y juguetón, el espacio de nuestra casa es muy pequeña por eso nuestra misión es encontrar la familia ideal para él y seguro que tú eres la persona indicada.",
        personality:["Cariñoso", "Inquieto", "Juguetón"],
        personalityImg:["https://i.ibb.co/XjwrCqd/cari-oso.png", 
                        "https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"Los Ageles California",
        ubication:"200-242 E Compton Blvd, Compton,",
        age:"2 Meses",
        sex:"male"

    },
    {
        id: 2,
        img: "https://i.ibb.co/k5DjwmG/perros-3.png",
        name: "Papi",
        type:"Dog",
        race: "Chihuahua",
        history:"Papi es un perrito feliz y amoroso, tenemos muchos animales y lo molesta por eso nuestra misión es encontrar la familia ideal para él y seguro que tú eres la persona indicada.",
        personality:["Cariñoso", "Inquieto", "Juguetón"],
        personalityImg:["https://i.ibb.co/XjwrCqd/cari-oso.png", 
                        "https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"Texas",
        ubication:"2900-2908 Hickory St, Dallas,",
        age:"1 Mes",
        sex:"male"
    },
    {
        id: 3,
        img: "https://i.ibb.co/3fvNWbh/perros-1.png",
        name: "Rocky",
        type:"Dog",
        race: "Rottweiler",
        history:"Rocky es un perrito muy lindo y cariñoso, tiene 5 hermanitos más y por cuestiones de espacio y tiempo no podremos cuidar a todos, nuestra misión es encontrar la familia ideal para él y seguro que tú eres la persona indicada.",
        personality:["Cariñoso", "Inquieto", "Juguetón"],
        personalityImg:["https://i.ibb.co/XjwrCqd/cari-oso.png", 
                        "https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"New Mexico 31134",
        ubication:"4140 Parker Rd. Allentown,",
        age:"3 Meses",
        sex:"male"
    },
    {
        id: 4,
        img: "https://i.ibb.co/0KH02v4/perros-2.png",
        name: "Pelusa",
        type:"Dog",
        race: "Bichón frisé",
        history:"Pelusa es una perrita muy jugetona y cariñosa, viajamos mucho y no podemos cuidarla por eso nuestra misión es encontrar la familia ideal para él y seguro que tú eres la persona indicada.",
        personality:["Cariñoso", "Inquieto", "Juguetón"],
        personalityImg:["https://i.ibb.co/XjwrCqd/cari-oso.png", 
                        "https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"New York",
        ubication:"Lower Clinton Hill,",
        age:"2 Meses",
        sex:"female"
    },
    {
        id: 5,
        img: "https://i.ibb.co/f0YvVjg/gatos-2.png",
        name: "Matilde",
        type:"Cat",
        race: "British Shorthair",
        history:"Matilde es la mejor guarda espaldas, siempre esta hay para conversar y recibirá cada día con un fuerte cariño. Fue rescatada y busco una persona que le pueda dar todo el amor que ella necesita.",
        personality:["Juguetón", "Inquieto", "Tierno"],
        personalityImg:["https://i.ibb.co/9gJ9mb8/jugueton.png",
                        "https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/KWPh90s/tierno.png"],
        city:"4140 Parker Rd. Allentown,",
        ubication:"New Mexico 31134",
        age:"6 Meses",
        sex:"female"

    },
    {
        id: 6,
        img: "https://i.ibb.co/Ttsdm1V/gatos-4.png",
        name: "Pelusa",
        type:"Cat",
        race: "Birmano",
        history:"pelusa es un gato jugeton de 4 meses, que está buscando una familia que lo quiera y cuide mucho. Es muy cariñoso y le gusta mucho que lo acaricien.Pelusa se lleva muy bien con otros gatos y perros, y bebes.",
        personality:["Cariñoso", "Tierno", "Juguetón"],
        personalityImg:["https://i.ibb.co/XjwrCqd/cari-oso.png", 
                        "https://i.ibb.co/KWPh90s/tierno.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"Texas",
        ubication:"2900-2908 Hickory St, Dallas,",
        age:"1 Mes",
        sex:"male"
    },
    {
        id: 7,
        img: "https://i.ibb.co/znrhfpz/gatos-3.png",
        name: "Kity",
        type:"Cat",
        race: "Bombay",
        history:"Kity es una gata joven y juguetona que busca un hogar en el que pasar el resto de su vida. Es cariñosa y amorosa, y le encanta la compañia con otros aninimales !!!",
        personality:["Inquieto", "Tierno", "Juguetón"],
        personalityImg:["https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/KWPh90s/tierno.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"New Mexico 31134",
        ubication:"4140 Parker Rd. Allentown,",
        age:"3 Meses",
        sex:"female"
    },
    {
        id: 8,
        img: "https://i.ibb.co/qpzYwPD/gatos-1.png",
        name: "Bombón",
        type:"Cat",
        race: "Gato americano",
        history:"Bombon es un gato inquieto de 6 meses, le gusta jugar con otros animales y es muy cariñoso. ama a los bebés duerme mucho, no tenemos espacio para el asi que estamos buscando una familia para el.",
        personality:["Cariñoso", "Inquieto", "Juguetón"],
        personalityImg:["https://i.ibb.co/XjwrCqd/cari-oso.png", 
                        "https://i.ibb.co/QPBDpVb/inquieto.png", 
                        "https://i.ibb.co/9gJ9mb8/jugueton.png"],
        city:"New York",
        ubication:"Lower Clinton Hill,",
        age:"2 Meses",
        sex:"male"
    },
]